apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend-app
  namespace: trainer-portal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      name: backend-app
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: devops1renad/backend-trainer-portal:latest
          ports:
            - containerPort: 3000
          env:
            - name: DB_SERVER
              value: "devops1-capstone-queens-sqlserver.database.windows.net"
            - name: DB_PORT
              value: "1433"
            - name: DB_USER
              value: "queens-assignment"
            - name: DB_PASSWORD
              value: "m/2.71.0/do"   
            - name: DB_NAME
              value: "queens-db"
